## 1-Linear Regression 

Linear regression is the simplest and most widely used statistical technique for predictive modeling. It basically gives us an equation, where we have our features as independent variables, on which our target variable [sales in our case] is dependent upon.
this model just regression without using any regularization .
So what does the equation look like? Linear regression equation looks like this:


<img src="Capture.PNG">

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import median_absolute_error
from sklearn.metrics import mean_squared_error
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

In [13]:
BostonData=load_boston()

In [14]:
X=BostonData.data
Y=BostonData.target

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,shuffle=True,random_state=44)

In [35]:
"""
sklearn.linear_model.LinearRegression(*, fit_intercept=True, normalize=False,
copy_X=True, n_jobs=None)
"""

'\nsklearn.linear_model.LinearRegression(*, fit_intercept=True, normalize=False,\ncopy_X=True, n_jobs=None)\n'

In [16]:
LinearRegressionModel=LinearRegression(copy_X=True,n_jobs=-1,normalize=True,fit_intercept=True)
LinearRegressionModel.fit(X_train,y_train)

LinearRegression(n_jobs=-1, normalize=True)

In [17]:
print("Train Score : ",LinearRegressionModel.score(X_train,y_train))
print("Test Score : ",LinearRegressionModel.score(X_test,y_test))
print("Model Coef : ",LinearRegressionModel.coef_)

Train Score :  0.733565792886427
Test Score :  0.7521800808693158
Model Coef :  [-1.18000933e-01  5.23312473e-02 -3.42698066e-03  3.27003752e+00
 -1.97085281e+01  3.11609207e+00  1.98406750e-03 -1.78381648e+00
  3.08103483e-01 -1.11789998e-02 -9.60997408e-01  1.00743448e-02
 -5.75953939e-01]


In [18]:
Pred=LinearRegressionModel.predict(X_test)

In [21]:
print(Pred[:5])
print(y_test[:5])

[17.44218075 25.56161457 22.26808304 37.06364051 13.87846166]
[17.8 21.5 21.2 32.4 10.9]


## 2-Ridge Regression 

Ridge Regression is a technique for analyzing multiple regression data that suffer from multicollinearity. ... By adding a degree of bias to the regression estimates, ridge regression reduces the standard errors. It is hoped that the net effect will be to give estimates that are more reliable.
and use  regularization on it .

In [2]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import median_absolute_error
from sklearn.metrics import mean_squared_error
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split


In [3]:
Boston=load_boston()
X=Boston.data
Y=Boston.target

In [4]:
X.shape

(506, 13)

In [5]:
Y.shape

(506,)

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,shuffle=True,random_state=44)

In [7]:
"""
sklearn.linear_model.Ridge(alpha=1.0, *, fit_intercept=True, normalize=False,
copy_X=True, max_iter=None, tol=0.001, solver=’auto’,
random_state=None)
""" 

'\nsklearn.linear_model.Ridge(alpha=1.0, *, fit_intercept=True, normalize=False,\ncopy_X=True, max_iter=None, tol=0.001, solver=’auto’,\nrandom_state=None)\n'

In [30]:
RigdeLinearRegression=Ridge(alpha=0.001,random_state=44,normalize=True)

In [31]:
RigdeLinearRegression.fit(X_train,y_train)

Ridge(alpha=0.001, normalize=True, random_state=44)

In [32]:
print("Train Score : ",RigdeLinearRegression.score(X_train,y_train))
print("Test Score : ",RigdeLinearRegression.score(X_test,y_test))
print("Model Coef : ",RigdeLinearRegression.coef_)

Train Score :  0.7335621414182676
Test Score :  0.7526186896951919
Model Coef :  [-1.17315950e-01  5.18725055e-02 -4.92777610e-03  3.27659589e+00
 -1.95679579e+01  3.12450089e+00  1.86736826e-03 -1.77468317e+00
  3.03976981e-01 -1.09879936e-02 -9.59181799e-01  1.00717829e-02
 -5.74824835e-01]


In [33]:
Pred=RigdeLinearRegression.predict(X_test)

In [34]:
print(Pred[:5])
print(y_test[:5])

[17.45110884 25.54717191 22.2605587  37.03815952 13.88961397]
[17.8 21.5 21.2 32.4 10.9]


# 3-Lasso Regression 

Lasso regression is a type of linear regression that uses shrinkage. Shrinkage is where data values are shrunk towards a central point, like the mean. The lasso procedure encourages simple, sparse models (i.e. models with fewer parameters). This particular type of regression is well-suited for models showing high levels of muticollinearity or when you want to automate certain parts of model selection, like variable selection/parameter elimination.



In [36]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import median_absolute_error
from sklearn.metrics import mean_squared_error
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split


In [37]:
"""
sklearn.linear_model.Lasso(alpha=1.0, *, fit_intercept=True, normalize=False, precompute=False, copy_X=True, max_iter=1000, tol=0.0001,
warm_start=False, positive=False, random_state=None, selection=’cyclic’)

"""

'\nsklearn.linear_model.Lasso(alpha=1.0, *, fit_intercept=True, normalize=False, precompute=False, copy_X=True, max_iter=1000, tol=0.0001,\nwarm_start=False, positive=False, random_state=None, selection=’cyclic’)\n\n'

In [38]:
Boston=load_boston()
X=Boston.data
Y=Boston.target

In [39]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,shuffle=True,random_state=44)

In [40]:
LassoLinearRegression=Lasso(alpha=0.001,random_state=44,normalize=True)

In [41]:
LassoLinearRegression.fit(X_train,y_train)

Lasso(alpha=0.001, normalize=True, random_state=44)

In [42]:
print("Train Score : ",LassoLinearRegression.score(X_train,y_train))
print("Test Score : ",LassoLinearRegression.score(X_test,y_test))
print("Model Coef : ",LassoLinearRegression.coef_)

Train Score :  0.7333235338607809
Test Score :  0.7549601327479057
Model Coef :  [-1.09008558e-01  4.82730945e-02 -7.34656647e-03  3.26640978e+00
 -1.86750950e+01  3.17050864e+00  0.00000000e+00 -1.71805982e+00
  2.72531000e-01 -9.68513182e-03 -9.47837681e-01  9.88536830e-03
 -5.72985302e-01]


In [43]:
Pred=LassoLinearRegression.predict(X_test)

In [44]:
print(Pred[:5])
print(y_test[:5])

[17.46864825 25.37507854 22.24659641 36.85582831 14.14425785]
[17.8 21.5 21.2 32.4 10.9]


# 4-SGD Regression

The SGD regressor applies regularized linear model with SGD learning to build an estimator. A regularizer is a penalty (L1, L2, or Elastic Net) added to the loss function to shrink the model parameters. The SGD regressor works well with large-scale datasets. 

In [45]:
""" 
sklearn.linear_model.SGDRegressor(loss=’squared_loss’, *, penalty=’l2’, alpha=0.0001, l1_ratio=0.15, fit_intercept=True,
max_iter=1000, tol=0.001, shuffle=True, verbose=0, epsilon=0.1, random_state=None, learning_rate=’invscaling’, eta0=0.01, power_t=0.25,
early_stopping=False, validation_fraction=0.1,
n_iter_no_change=5, warm_start=False, average=False)


"""

' \nsklearn.linear_model.SGDRegressor(loss=’squared_loss’, *, penalty=’l2’, alpha=0.0001, l1_ratio=0.15, fit_intercept=True,\nmax_iter=1000, tol=0.001, shuffle=True, verbose=0, epsilon=0.1, random_state=None, learning_rate=’invscaling’, eta0=0.01, power_t=0.25,\nearly_stopping=False, validation_fraction=0.1,\nn_iter_no_change=5, warm_start=False, average=False)\n\n\n'

In [46]:
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import median_absolute_error
from sklearn.metrics import mean_squared_error
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

In [47]:
Boston=load_boston()
X=Boston.data
Y=Boston.target

In [48]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,shuffle=True,random_state=44)

In [49]:
SGDLinearRegression=SGDRegressor(alpha=0.001,random_state=44,penalty='l2',loss='huber')

In [50]:
SGDLinearRegression.fit(X_train,y_train)

SGDRegressor(alpha=0.001, loss='huber', random_state=44)

In [51]:
print("Train Score : ",SGDLinearRegression.score(X_train,y_train))
print("Test Score : ",SGDLinearRegression.score(X_test,y_test))
print("Model Coef : ",SGDLinearRegression.coef_)

Train Score :  -19.791563659514203
Test Score :  -19.497772254898486
Model Coef :  [-0.01795289  0.1544739  -0.11972102  0.01007805  0.00606359  0.21668749
  0.13292396  0.00225464  0.03002012 -0.06038238  0.05099647  0.0042471
 -0.55124098]


In [52]:
Pred=SGDLinearRegression.predict(X_test)

In [53]:
print(Pred[:5])
print(y_test[:5])

[-14.56387401 -11.74213482 -36.58282398  -3.29289415 -37.4011705 ]
[17.8 21.5 21.2 32.4 10.9]


## 5-Neural Network in Regression 

In [15]:
from sklearn.neural_network import MLPRegressor 
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error 

In [16]:
"""

neural_network.MLPRegressor(hidden_layer_sizes=(100, ), activation=’relu’, *, solver=’adam’, alpha=0.0001, batch_size=’auto’, learning_rate=’constant’, learning_rate_init=0.001,
power_t=0.5, max_iter=200, shuffle=True,
random_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True,
early_stopping=False, validation_fraction=0.1,
beta_1=0.9, beta_2=0.999, epsilon=1e-08,
n_iter_no_change=10, max_fun=15000)

"""

'\n\nneural_network.MLPRegressor(hidden_layer_sizes=(100, ), activation=’relu’, *, solver=’adam’, alpha=0.0001, batch_size=’auto’, learning_rate=’constant’, learning_rate_init=0.001,\npower_t=0.5, max_iter=200, shuffle=True,\nrandom_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True,\nearly_stopping=False, validation_fraction=0.1,\nbeta_1=0.9, beta_2=0.999, epsilon=1e-08,\nn_iter_no_change=10, max_fun=15000)\n\n'

In [23]:
Boston=load_boston()
X=Boston.data
Y=Boston.target

In [24]:
X.shape

(506, 13)

In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.33,random_state=44,shuffle=True)

In [26]:
print(X_train.shape)
print(X_test.shape)

(339, 13)
(167, 13)


In [32]:
MLPRegressorModel=MLPRegressor(activation='relu',solver='lbfgs',learning_rate='constant',early_stopping=False,alpha=0.0001
                               ,hidden_layer_sizes=(100,3),random_state=44,max_iter=10000)
MLPRegressorModel.fit(X_train,y_train)

MLPRegressor(hidden_layer_sizes=(100, 3), max_iter=10000, random_state=44,
             solver='lbfgs')

In [34]:
print("Train Score : ",MLPRegressorModel.score(X_train,y_train))
print("Test Score : ",MLPRegressorModel.score(X_test,y_test))
print("num of iteration : ",MLPRegressorModel.n_iter_)

Train Score :  0.9458371205964735
Test Score :  0.8349831335155904
num of iteration :  8665


In [35]:
Pred=MLPRegressorModel.predict(X_test)

In [36]:
print(Pred[:5])
print(y_test[:5])

[18.53500908 20.24965119 25.76524172 31.02156487  7.24631621]
[17.8 21.5 21.2 32.4 10.9]
